"""OCR model migration 3

Revision ID: 9b0211a53c03
Revises: 72eca5d38062
Create Date: 2025-10-10 11:54:53.331167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b0211a53c03'
down_revision: Union[str, Sequence[str], None] = '72eca5d38062'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ocr_title',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ocr_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['title_id'], ['ocr_title.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ocr_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ocr_items_id', sa.UUID(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ocr_items_id'], ['ocr_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ocr_data')
    op.drop_table('ocr_items')
    op.drop_table('user')
    op.drop_table('ocr_title')
    # ### end Alembic commands ###
